# Generated by Django 4.0.6 on 2022-07-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('external_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID пользователя в Telegram')),
                ('nickname', models.TextField(verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('quest_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID задания')),
                ('name_quest', models.CharField(max_length=100, verbose_name='Название задания')),
                ('text_quest', models.TextField(verbose_name='Текст задания')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('key_auto', models.CharField(max_length=19, verbose_name='Ключ авторизации')),
                ('user_id', models.CharField(default=0, max_length=20, primary_key=True, serialize=False, verbose_name='ID пользователя в Telegram')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fewapp.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ad', models.DateTimeField(auto_now_add=True, verbose_name='Время принятия')),
                ('date_comletion', models.DateTimeField(verbose_name='Время завершения')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fewapp.questions', verbose_name='Задание')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fewapp.user', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Задание пользователя',
                'verbose_name_plural': 'Задания пользователей',
            },
        ),
    ]
