# Generated by Django 4.0.6 on 2022-08-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0002_alter_userquestions_date_comletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=100, verbose_name='Название торговой точки')),
                ('point_adress', models.CharField(max_length=100, verbose_name='Название торговой точки')),
                ('point_number', models.CharField(max_length=20, verbose_name='Название торговой точки')),
                ('photo_stand', models.ImageField(upload_to='images/')),
                ('active_led', models.CharField(max_length=5, verbose_name='Горит ли LED')),
                ('competitor', models.TextField(verbose_name='Конкуренты на ТТ')),
                ('mark_point', models.IntegerField(verbose_name='Оценка ТТ')),
                ('stand_column', models.CharField(max_length=5, verbose_name='Стенд-колонна')),
                ('handout', models.CharField(max_length=5, verbose_name='Раздаточный материал')),
                ('contacts_point', models.TextField(verbose_name='Контакты ТТ')),
            ],
            options={
                'verbose_name': 'Торговая точка',
                'verbose_name_plural': 'Торговые точки',
            },
        ),
    ]
