# Generated by Django 4.0.6 on 2022-08-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0003_pointsales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsales',
            name='active_led',
        ),
        migrations.RemoveField(
            model_name='pointsales',
            name='competitor',
        ),
        migrations.RemoveField(
            model_name='pointsales',
            name='contacts_point',
        ),
        migrations.RemoveField(
            model_name='pointsales',
            name='handout',
        ),
        migrations.RemoveField(
            model_name='pointsales',
            name='mark_point',
        ),
        migrations.RemoveField(
            model_name='pointsales',
            name='point_adress',
        ),
        migrations.RemoveField(
            model_name='pointsales',
            name='point_name',
        ),
        migrations.RemoveField(
            model_name='pointsales',
            name='point_number',
        ),
        migrations.RemoveField(
            model_name='pointsales',
            name='stand_column',
        ),
    ]
