# Generated by Django 4.0.6 on 2022-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0004_remove_pointsales_active_led_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsales',
            name='point_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID торговой точки'),
        ),
    ]
