# Generated by Django 4.0.6 on 2022-08-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0005_pointsales_point_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsales',
            name='photo_stand',
            field=models.CharField(max_length=200, verbose_name='Фото стенда'),
        ),
    ]
