# Generated by Django 4.0.6 on 2022-08-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0006_alter_pointsales_photo_stand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsales',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pointsales',
            name='photo_stand',
        ),
        migrations.AddField(
            model_name='pointsales',
            name='active_led',
            field=models.CharField(max_length=5, null=True, verbose_name='Горит ли LED'),
        ),
        migrations.AddField(
            model_name='pointsales',
            name='competitor',
            field=models.TextField(null=True, verbose_name='Конкуренты на ТТ'),
        ),
        migrations.AddField(
            model_name='pointsales',
            name='contacts_point',
            field=models.TextField(null=True, verbose_name='Контакты ТТ'),
        ),
        migrations.AddField(
            model_name='pointsales',
            name='handout',
            field=models.CharField(max_length=5, null=True, verbose_name='Раздаточный материал'),
        ),
        migrations.AddField(
            model_name='pointsales',
            name='mark_point',
            field=models.IntegerField(null=True, verbose_name='Оценка ТТ'),
        ),
        migrations.AddField(
            model_name='pointsales',
            name='point_adress',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес ТТ'),
        ),
        migrations.AddField(
            model_name='pointsales',
            name='point_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название торговой точки'),
        ),
        migrations.AddField(
            model_name='pointsales',
            name='point_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер ТТ на рынке'),
        ),
        migrations.AddField(
            model_name='pointsales',
            name='stand_column',
            field=models.CharField(max_length=5, null=True, verbose_name='Стенд-колонна'),
        ),
        migrations.AlterField(
            model_name='pointsales',
            name='point_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID торговой точки'),
        ),
    ]
