# Generated by Django 4.0.6 on 2022-08-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0007_remove_pointsales_id_remove_pointsales_photo_stand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsales',
            name='point_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID торговой точки'),
        ),
        migrations.AlterField(
            model_name='pointsales',
            name='point_name',
            field=models.CharField(max_length=100, verbose_name='Название торговой точки'),
        ),
    ]
