# Generated by Django 4.0.6 on 2022-08-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0008_alter_pointsales_point_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointsales',
            old_name='point_adress',
            new_name='point_address',
        ),
        migrations.AddField(
            model_name='pointsales',
            name='metro',
            field=models.CharField(max_length=100, null=True, verbose_name='Станция метро'),
        ),
    ]
