# Generated by Django 4.0.6 on 2022-08-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0010_remove_pointsales_contacts_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsales',
            name='contacts_point_email',
            field=models.CharField(max_length=12, null=True, verbose_name='Email контакного лица'),
        ),
    ]
