# Generated by Django 4.0.6 on 2022-08-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fewapp', '0011_pointsales_contacts_point_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsales',
            name='point_photo',
            field=models.CharField(max_length=100, null=True, verbose_name='Фото стенда'),
        ),
        migrations.AlterField(
            model_name='pointsales',
            name='contacts_point_email',
            field=models.CharField(max_length=30, null=True, verbose_name='Email контакного лица'),
        ),
    ]
